{{- if .Values.postgresStandalone.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "SkautRegistraceChart.fullname" . }}-postgres
  labels:
    {{- include "SkautRegistraceChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "SkautRegistraceChart.name" . }}-postgres
  serviceName: "postgres-service"
  template:
    metadata:
      labels:
        app: {{ include "SkautRegistraceChart.name" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: '{{ printf "%s:%s" .Values.postgres.repository .Values.postgres.tag }}'
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          ports:
            - containerPort: 5432
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secret.name }}
                  key: {{ .Values.postgres.secret.key }}
            - name: POSTGRES_DB
              value: "{{ .Values.postgresService.db }}"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data

          ### Probes ###
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3

  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        # Optional: make storageClass configurable
        # storageClassName: {{ .Values.postgres.storageClass | default "" }}
{{- end }}
