replicaCount: 1


spring_image:
  repository: electro3lite/skautregistrace-spring
  pullPolicy: IfNotPresent
  tag: latest

postgres:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: 16-alpine
  user: "postgres"
  password: "changeMe" # intended to be rewriten with --set postgres.password="ActualPwd"
  db: "vlcatashed"

service:
  type: NodePort
  port: 8080
serviceAccount:
  create: false
  name: ""
ingress:
  enabled: false


