
spring:
  repository: electro3lite/skautregistrace-spring
  pullPolicy: IfNotPresent
  tag: latest #for local test only, in prod should be version number
  replicaCount: 1

  service:
    name: "spring-service"
    type: NodePort
    protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 30000


### POSTGRES ###
# Only one should be enabled: Standalone/Cluster
postgresStandalone:
  enabled: false
  repository: postgres
  pullPolicy: IfNotPresent
  tag: 16-alpine
  replicaCount: 1
  user: "postgres"
  db: "vlcatasched"
  secret: # the secret should be created before helm install, kubectl craete secret generic pwd-postgres --from-literal=POSTGRES_PASSWORD ="changeMe"
    name: pwd-postgres
    key:  POSTGRES_PASSWORD

  service:
    name: "postgres-service"
    clusterIP: None
    protocol: "TCP"
    port: 5432
    targetPort: 5432

postgresCluster:
  enabled: true
  name: acid-minimal-cluster
  teamId: acid
  volumeSize: 1Gi
  numberOfInstances: 3
  users:
    zalando:
      - superuser
      - createdb
    foo_user: []
  databases:
    vlcatasched: postgres
    foo: zalando
  preparedDatabases:
    bar: {}
  postgresqlVersion: "16"

resources:
  spring:
    requests:
      cpu: 100m
      memory: 450Mi
    limits:
      cpu: 500m
      memory: 1Gi
  postgres:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
