{{- if .Values.postgresCluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresCluster.pgpool.service.name }}
spec:
  ports:
    - port: {{ .Values.postgresCluster.pgpool.service.port }}
  selector:
    app: pgpool
{{- end }}
