{{- if .Values.postgresCluster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
spec:
  replicas: {{ .Values.postgresCluster.pgpool.replicaCount }}
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
        - name: pgpool
          image: "{{ .Values.postgresCluster.pgpool.image.repository }}:{{ .Values.postgresCluster.pgpool.image.tag }}"
          ports:
            - containerPort: 9999
          env:
            # Backends
            - name: PGPOOL_PARAMS_BACKEND_HOSTNAME0
              value: "{{ .Values.postgresCluster.pgpool.config.backend.master }}"
            - name: PGPOOL_PARAMS_BACKEND_PORT0
              value: "5432"
            - name: PGPOOL_PARAMS_BACKEND_WEIGHT0
              value: "1"
            - name: PGPOOL_PARAMS_BACKEND_FLAG0
              value: "DISALLOW_TO_FAILOVER"

            - name: PGPOOL_PARAMS_BACKEND_HOSTNAME1
              value: "{{ .Values.postgresCluster.pgpool.config.backend.replica }}"
            - name: PGPOOL_PARAMS_BACKEND_PORT1
              value: "5432"
            - name: PGPOOL_PARAMS_BACKEND_WEIGHT1
              value: "1"
            - name: PGPOOL_PARAMS_BACKEND_FLAG1
              value: "DISALLOW_TO_FAILOVER"

            # Credentials
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do"
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do"
                  key: password

            # Pgpool-II behavior flags
#            - name: PGPOOL_DATABASE
#              value: "postgres"
            - name: PGPOOL_PARAMS_health_check_user
              valueFrom:
                secretKeyRef:
                  name: "postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do"
                  key: username
            - name: PGPOOL_PARAMS_health_check_password
              valueFrom:
                secretKeyRef:
                  name: "postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do"
                  key: password
            - name: PGPOOL_SERVICE_PORT
              value: "9999"
            - name: PGPOOL_ENABLE_LOAD_BALANCE
              value: "true"
            - name: PGPOOL_ENABLE_POOL_HBA
              value: "true"
            - name: PGPOOL_HEALTH_CHECK_PERIOD
              value: "10"
            - name: PGPOOL_HEALTH_CHECK_TIMEOUT
              value: "20"
{{- end }}
