apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "SkautRegistraceChart.fullname" . }}-postgres
  labels:
    {{- include "SkautRegistraceChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "SkautRegistraceChart.name" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "SkautRegistraceChart.name" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: '{{ printf "%s:%s" .Values.postgres.repository .Values.postgres.tag }}'
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.db }}"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: db-data
          emptyDir: {}
