apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "SkautRegistraceChart.fullname" . }}-postgres
  labels:
    {{- include "SkautRegistraceChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "SkautRegistraceChart.name" . }}-postgres
  serviceName: {{ include "SkautRegistraceChart.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "SkautRegistraceChart.name" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: '{{ printf "%s:%s" .Values.postgres.repository .Values.postgres.tag }}'
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secret.name }}
                  key:  {{ .Values.postgres.secret.key }}
#              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.db }}"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

