apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
spec:
  clusterIP: {{ .Values.postgres.service.clusterIP }}
  selector:
    app: {{ include "SkautRegistraceChart.name" . }}-postgres
  ports:
    - protocol: {{ .Values.postgres.service.protocol }}
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
