apiVersion: v1
kind: Service
metadata:
  name: "postgres-service"
spec:
  type: ClusterIP
  selector:
    app: {{ include "SkautRegistraceChart.name" . }}-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
