apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresService.name }}
spec:
  clusterIP: {{ .Values.postgresService.clusterIP }}
  selector:
    app: {{ include "SkautRegistraceChart.name" . }}-postgres
  ports:
    - protocol: {{ .Values.postgresService.protocol }}
      port: {{ .Values.postgresService.port }}
      targetPort: {{ .Values.postgresService.targetPort }}
