apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: skaut-gateway
spec:
  gatewayClassName: envoy-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 8088
