apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spring.service.name }}
spec:
  type: {{ .Values.spring.service.type }}
  selector:
    app: {{ include "SkautRegistraceChart.name" . }}-spring
  ports:
    - protocol: {{ .Values.spring.service.protocol }}
      port: {{ .Values.spring.service.port }}
      targetPort: {{ .Values.spring.service.targetPort }}
      nodePort: {{ .Values.spring.service.nodePort }}
#  sessionAffinity: ClientIP # Sticky Ip session
