apiVersion: v1
kind: Service
metadata:
  name: "spring-service"
spec:
  type: NodePort
  selector:
    app: {{ include "SkautRegistraceChart.name" . }}-spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
#  sessionAffinity: ClientIP # Sticky Ip session
